import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">SolnamesViewDomain</Link>
        </li>
        <li>
          <Link to="/domainclickoverview">DomainClickOverView</Link>
        </li>
        <li>
          <Link to="/viewdetails">ViewDetails</Link>
        </li>
        <li>
          <Link to="/domainexplorefullopen">DOmainexplorefullopen</Link>
        </li>
        <li>
          <Link to="/buymodal">BuyModal</Link>
        </li>
        <li>
          <Link to="/solnameschoosetokentoconnectwith">
            SolnamesChoosetokentoconnectwith
          </Link>
        </li>
        <li>
          <Link to="/solnamescheckout">SolnamesCheckout</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
